[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/invite"
  to = "https://discord.com/api/oauth2/authorize?client_id=820018018490646538&permissions=2048&scope=applications.commands%20bot"
  status = 301